"""empty message

Revision ID: 026f06747059
Revises: 99c9399a3111
Create Date: 2023-11-08 17:37:17.044432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '026f06747059'
down_revision = '99c9399a3111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coursenotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coursenotes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tex', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(length=600), autoincrement=False, nullable=False),
    sa.Column('resp_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='coursenotes_course_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='coursenotes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='coursenotes_pkey')
    )
    # ### end Alembic commands ###
