"""empty message

Revision ID: 0d4e81d1a5f7
Revises: e1a6b99de2f5
Create Date: 2023-11-15 17:19:25.566886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4e81d1a5f7'
down_revision = 'e1a6b99de2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('created_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solutions', 'created_id')
    # ### end Alembic commands ###
