"""empty message

Revision ID: 1226228a8ad3
Revises: 
Create Date: 2023-10-11 14:37:46.149805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1226228a8ad3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('professor', sa.Boolean(), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('gpa', sa.String(length=255), nullable=True),
    sa.Column('degree_timeline', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('role_title', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.BigInteger(), nullable=True),
    sa.Column('end_Date', sa.Integer(), nullable=True),
    sa.Column('present_role', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accomplishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=600), nullable=True),
    sa.Column('place', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('subject', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=600), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('advisor', sa.String(length=600), nullable=True),
    sa.Column('subject', sa.String(length=600), nullable=True),
    sa.Column('date', sa.String(length=255), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url1', sa.Text(), nullable=True),
    sa.Column('url2', sa.Text(), nullable=True),
    sa.Column('url3', sa.Text(), nullable=True),
    sa.Column('url4', sa.Text(), nullable=True),
    sa.Column('url5', sa.Text(), nullable=True),
    sa.Column('url6', sa.Text(), nullable=True),
    sa.Column('url7', sa.Text(), nullable=True),
    sa.Column('url8', sa.Text(), nullable=True),
    sa.Column('url9', sa.Text(), nullable=True),
    sa.Column('url10', sa.Text(), nullable=True),
    sa.Column('url11', sa.Text(), nullable=True),
    sa.Column('url12', sa.Text(), nullable=True),
    sa.Column('url13', sa.Text(), nullable=True),
    sa.Column('url14', sa.Text(), nullable=True),
    sa.Column('url15', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('comment', sa.String(length=600), nullable=False),
    sa.Column('root', sa.Boolean(), nullable=True),
    sa.Column('resp_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courseusers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('folderusers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('publicationcitations',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['publications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('publicationusers',
    sa.Column('citation_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicationusers')
    op.drop_table('publicationcitations')
    op.drop_table('folderusers')
    op.drop_table('courseusers')
    op.drop_table('publications')
    op.drop_table('posts')
    op.drop_table('journals')
    op.drop_table('folders')
    op.drop_table('education')
    op.drop_table('courses')
    op.drop_table('accomplishments')
    op.drop_table('users')
    op.drop_table('citations')
    # ### end Alembic commands ###
