"""empty message

Revision ID: 184cf5dd5033
Revises: e31145a43de1
Create Date: 2023-11-07 15:34:03.312823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184cf5dd5033'
down_revision = 'e31145a43de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_confirmed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed_on')
    op.drop_column('users', 'is_confirmed')
    # ### end Alembic commands ###
