"""empty message

Revision ID: 1b287d3a53b3
Revises: 
Create Date: 2023-10-20 17:17:42.371131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b287d3a53b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('professor', sa.Boolean(), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('gpa', sa.String(length=255), nullable=True),
    sa.Column('degree_timeline', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('role_title', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.BigInteger(), nullable=True),
    sa.Column('end_Date', sa.Integer(), nullable=True),
    sa.Column('present_role', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accomplishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=600), nullable=True),
    sa.Column('lastname', sa.String(length=600), nullable=True),
    sa.Column('highest_degree', sa.String(length=255), nullable=True),
    sa.Column('publications', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('awards', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('subject', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('degree_undergrad', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('university_undergrad', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('degree_masters', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('university_masters', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('degree_postdoc', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('university_postdoc', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('doctoral_advisor', sa.String(length=600), nullable=True),
    sa.Column('subject', sa.String(length=600), nullable=True),
    sa.Column('date', sa.String(length=255), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('userId2', sa.Integer(), nullable=True),
    sa.Column('request', sa.Boolean(), nullable=True),
    sa.Column('requestTime', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profileImage', sa.String(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('userId2', sa.Integer(), nullable=True),
    sa.Column('friends', sa.Boolean(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('friendTime', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userId2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journalscommittee',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('comment', sa.String(length=600), nullable=False),
    sa.Column('research', sa.Boolean(), nullable=True),
    sa.Column('root', sa.Boolean(), nullable=True),
    sa.Column('resp_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courseusers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('publicationcitations',
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('citation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], )
    )
    op.create_table('publicationusers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicationusers')
    op.drop_table('publicationcitations')
    op.drop_table('courseusers')
    op.drop_table('publications')
    op.drop_table('posts')
    op.drop_table('journalscommittee')
    op.drop_table('friends')
    op.drop_table('friend_requests')
    op.drop_table('folders')
    op.drop_table('education')
    op.drop_table('courses')
    op.drop_table('citations')
    op.drop_table('accomplishments')
    op.drop_table('users')
    op.drop_table('journals')
    # ### end Alembic commands ###
