"""empty message

Revision ID: 1ed6fc0390f6
Revises: 971aaf8c3fbd
Create Date: 2023-10-30 22:38:49.551325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed6fc0390f6'
down_revision = '971aaf8c3fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'comment',
               existing_type=sa.VARCHAR(length=600),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'comment',
               existing_type=sa.VARCHAR(length=600),
               nullable=False)
    # ### end Alembic commands ###
