"""empty message

Revision ID: 440ad3c88819
Revises: ab0818238f1f
Create Date: 2023-11-06 14:44:00.862860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '440ad3c88819'
down_revision = 'ab0818238f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('undergrad', postgresql.ARRAY(sa.JSON()), nullable=True))
    op.add_column('education', sa.Column('masters', postgresql.ARRAY(sa.JSON()), nullable=True))
    op.add_column('education', sa.Column('postdoc', postgresql.ARRAY(sa.JSON()), nullable=True))
    op.drop_column('education', 'subject')
    op.drop_column('education', 'degree_postdoc')
    op.drop_column('education', 'date')
    op.drop_column('education', 'university_undergrad')
    op.drop_column('education', 'degree_masters')
    op.drop_column('education', 'degree_undergrad')
    op.drop_column('education', 'university_masters')
    op.drop_column('education', 'university_postdoc')
    op.drop_column('education', 'doctoral_advisor')
    op.drop_column('education', 'thesis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('thesis', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('doctoral_advisor', sa.VARCHAR(length=600), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('university_postdoc', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('university_masters', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('degree_undergrad', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('degree_masters', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('university_undergrad', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('date', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('degree_postdoc', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('subject', sa.VARCHAR(length=600), autoincrement=False, nullable=True))
    op.drop_column('education', 'postdoc')
    op.drop_column('education', 'masters')
    op.drop_column('education', 'undergrad')
    # ### end Alembic commands ###
