"""empty message

Revision ID: 44947dd7c8c6
Revises: d833a48fc164
Create Date: 2023-11-14 15:16:42.029337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44947dd7c8c6'
down_revision = 'd833a48fc164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assignments', sa.Column('solution_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignments', 'solutions', ['solution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'solution_id')
    op.drop_table('solutions')
    # ### end Alembic commands ###
