"""empty message

Revision ID: 7d55266bc401
Revises: 8e203c7e9096
Create Date: 2023-11-13 17:50:48.018110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d55266bc401'
down_revision = '8e203c7e9096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'images')
    # ### end Alembic commands ###
