"""empty message

Revision ID: 88fb4cfb849b
Revises: d03769e7f3a1
Create Date: 2023-11-14 20:30:33.528169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fb4cfb849b'
down_revision = 'd03769e7f3a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('submission', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solutions', 'submission')
    # ### end Alembic commands ###
