"""empty message

Revision ID: 8c7a509e4679
Revises: 91cf9299ecd2
Create Date: 2023-11-09 19:00:01.938301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c7a509e4679'
down_revision = '91cf9299ecd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('grades', postgresql.ARRAY(sa.JSON()), nullable=True))
    op.add_column('courses', sa.Column('announcements', postgresql.ARRAY(sa.JSON()), nullable=True))
    op.add_column('courses', sa.Column('syllabus', postgresql.ARRAY(sa.JSON()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'syllabus')
    op.drop_column('courses', 'announcements')
    op.drop_column('courses', 'grades')
    # ### end Alembic commands ###
