"""empty message

Revision ID: 8e203c7e9096
Revises: 71a09e57f083
Create Date: 2023-11-13 16:04:04.442904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e203c7e9096'
down_revision = '71a09e57f083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_post_id_fkey', 'courses', type_='foreignkey')
    op.drop_column('courses', 'post_id')
    op.add_column('posts', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'course_id')
    op.add_column('courses', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('courses_post_id_fkey', 'courses', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
