"""empty message

Revision ID: 90dc506bd60a
Revises: e3a71cb5cb25
Create Date: 2023-11-03 20:35:04.864470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90dc506bd60a'
down_revision = 'e3a71cb5cb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('abstract', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'abstract')
    # ### end Alembic commands ###
