"""empty message

Revision ID: 91cf9299ecd2
Revises: 026f06747059
Create Date: 2023-11-08 17:39:00.232543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91cf9299ecd2'
down_revision = '026f06747059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'post_id')
    # ### end Alembic commands ###
