"""empty message

Revision ID: ab0818238f1f
Revises: 90dc506bd60a
Create Date: 2023-11-06 13:03:44.786069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0818238f1f'
down_revision = '90dc506bd60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accomplishments', sa.Column('bio', sa.Text(), nullable=True))
    op.drop_column('accomplishments', 'firstname')
    op.drop_column('accomplishments', 'highest_degree')
    op.drop_column('accomplishments', 'lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accomplishments', sa.Column('lastname', sa.VARCHAR(length=600), autoincrement=False, nullable=True))
    op.add_column('accomplishments', sa.Column('highest_degree', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('accomplishments', sa.Column('firstname', sa.VARCHAR(length=600), autoincrement=False, nullable=True))
    op.drop_column('accomplishments', 'bio')
    # ### end Alembic commands ###
