"""empty message

Revision ID: d2b643a91efc
Revises: 44947dd7c8c6
Create Date: 2023-11-14 17:05:29.081540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b643a91efc'
down_revision = '44947dd7c8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_constraint('assignments_solution_id_fkey', 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'solution_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('solution_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('assignments_solution_id_fkey', 'assignments', 'solutions', ['solution_id'], ['id'])
    op.drop_column('assignments', 'active')
    # ### end Alembic commands ###
