"""empty message

Revision ID: e31145a43de1
Revises: 440ad3c88819
Create Date: 2023-11-07 02:46:34.274506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31145a43de1'
down_revision = '440ad3c88819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('commentsreplies_replyId_fkey', 'commentsreplies', type_='foreignkey')
    op.drop_constraint('commentsreplies_commentId_fkey', 'commentsreplies', type_='foreignkey')
    op.create_foreign_key(None, 'commentsreplies', 'posts', ['replyId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'commentsreplies', 'posts', ['commentId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commentsreplies', type_='foreignkey')
    op.drop_constraint(None, 'commentsreplies', type_='foreignkey')
    op.create_foreign_key('commentsreplies_commentId_fkey', 'commentsreplies', 'posts', ['commentId'], ['id'])
    op.create_foreign_key('commentsreplies_replyId_fkey', 'commentsreplies', 'posts', ['replyId'], ['id'])
    # ### end Alembic commands ###
