"""empty message

Revision ID: e3a71cb5cb25
Revises: 1ed6fc0390f6
Create Date: 2023-10-31 17:21:42.203973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a71cb5cb25'
down_revision = '1ed6fc0390f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentsreplies',
    sa.Column('commentId', sa.Integer(), nullable=False),
    sa.Column('replyId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commentId'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['replyId'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('commentId', 'replyId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commentsreplies')
    # ### end Alembic commands ###
